### ISSUE TITLE
Issues with uikit sample

### ISSUE THREAD

**Issue by StefMa** [JetBrains/kotlin-native#1128]
Hi guys,

I've just downloaded 0.4.0 from the release page and wanted to test the uikit sample.
Unfortunately I run into some trouble:
I changed the bundle id and use my provision profile.
After I run, I got a error that the "konan" plugin can't be found.

I fixed it by adding
```gradle
buildscript {
  repositories {
    mavenCentral()
    maven {
      url "https://dl.bintray.com/jetbrains/kotlin-native-dependencies"
    }
  }

  dependencies {
    classpath "org.jetbrains.kotlin:kotlin-native-gradle-plugin:+"
  }
}
```
this to the `build.gradle`.

It works in the source-samples because we have the root `build.gradle` which has already the `repositories` defined. 

The next point, which  I can't help me.
After running I got:
> cp: /Users/$USER/Developer/KotlinNative/kotlin-native-0.4/samples/uikit/build/konan/bin/app.kexe: No such file or directory

I found out, that the `app.kexe` exist. But in 
> cp: /Users/$USER/Developer/KotlinNative/kotlin-native-0.4/samples/uikit/build/konan/bin/iphone/app.kexe: No such file or directory

(Not the **iphone** here 🙃 )

How can I solve that issue?

## Update
I've just build it and moved the files from the `iphone/` dir on dir up.
This helps and "fix the issue".
But now I got:
<img width="408" alt="bildschirmfoto 2017-12-11 um 16 58 25" src="https://user-images.githubusercontent.com/10229883/33840201-87a9446a-de94-11e7-8519-5bffbaf2b7d7.png">

How can I run the uikit sample without issues? :D

**Comment by olonho** [comment]
0.4 supports running on the phone only, you seems to run it on  the simulator.

**Comment by StefMa** [comment]
Ah you mean I need a hardware device?
Hmm sad that I need a real iPhone 😒...

**Comment by olonho** [comment]
Please wait for upcoming v0.5, you may also test drive https://github.com/JetBrains/kotlin-native/pull/1134

**Comment by StefMa** [comment]
Hi @olonho 

thanks for the #1134 hint 👍 

I've tried it but without success.
I've done the following:
**Build kotlin-native from the sources** (on the #1134  branch of course):
```
./gradlew dependencies:update
./gradlew dist distPlatformLibs
# Then added the dist/bin to my `~/.bash_profile`
```

Then I opened the sample from the 0.4 dir.
Still get the same error.

Then I tried to open the sample from the sources dir.
Here I get a Exception:
> Server returned HTTP response code: 403 for URL: https://download.jetbrains.com/kotlin/native/libffi-3.2.1-1-darwin-ios_sim.tar.gz
<details>

```
exception: org.jetbrains.kotlin.konan.util.DependencyDownloader$HTTPResponseException: Server returned HTTP response code: 403 for URL: https://download.jetbrains.com/kotlin/native/libffi-3.2.1-1-darwin-ios_sim.tar.gz
	at org.jetbrains.kotlin.konan.util.DependencyDownloader.checkHTTPResponse(DependencyDownloader.kt:67)
	at org.jetbrains.kotlin.konan.util.DependencyDownloader.tryDownload(DependencyDownloader.kt:144)
	at org.jetbrains.kotlin.konan.util.DependencyDownloader.download(DependencyDownloader.kt:180)
	at org.jetbrains.kotlin.konan.util.DependencyDownloader.download$default(DependencyDownloader.kt:158)
	at org.jetbrains.kotlin.konan.util.DependencyProcessor.processDependency(DependencyProcessor.kt:176)
	at org.jetbrains.kotlin.konan.util.DependencyProcessor.run(DependencyProcessor.kt:196)
	at org.jetbrains.kotlin.backend.konan.KonanConfig.prepareDependencies(KonanConfig.kt:51)
	at org.jetbrains.kotlin.backend.konan.KonanConfig.<init>(KonanConfig.kt:58)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:52)
	at org.jetbrains.kotlin.cli.bc.K2Native.doExecute(K2Native.kt:41)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:107)
	at org.jetbrains.kotlin.cli.common.CLICompiler.execImpl(CLICompiler.java:51)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:92)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:70)
	at org.jetbrains.kotlin.cli.common.CLITool.exec(CLITool.kt:36)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMainNoExit(CLITool.kt:157)
	at org.jetbrains.kotlin.cli.common.CLITool$Companion.doMain(CLITool.kt:148)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:168)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion$main$1.invoke(K2Native.kt:159)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profileIf(util.kt:33)
	at org.jetbrains.kotlin.backend.konan.util.UtilKt.profile(util.kt:28)
	at org.jetbrains.kotlin.cli.bc.K2Native$Companion.main(K2Native.kt:161)
	at org.jetbrains.kotlin.cli.bc.K2NativeKt.main(K2Native.kt:173)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:115)

```

</details>

**Comment by SvyatoslavScherbina** [comment]
Hi @StefMa 

> Server returned HTTP response code: 403 for URL: 
> https://download.jetbrains.com/kotlin/native/libffi-3.2.1-1-darwin-ios_sim.tar.gz

We have fixed this issue.

> :uikit:compileKonanAppIphone_simexception: java.nio.file.NoSuchFileException: 
> /Users/$USER/Developer/KotlinNative/source/dist/konan/targets/iphone_sim/native

Please try to build Kotlin/Native with
```
./gradlew dependencies:update
./gradlew crossDist crossDistPlatformLibs
```
(would require a lot of time).

**Comment by StefMa** [comment]
<img width="299" alt="geist_1513173647652" src="https://user-images.githubusercontent.com/10229883/33942555-9f3be6b8-e016-11e7-9fb8-8a3f8e05c2b2.png">
Do I have more to say? 😝 

Thanks its working now... after a very long build session ⏳ 
![bildschirmfoto 2017-12-13 um 15 03 21](https://user-images.githubusercontent.com/10229883/33942628-c9b3ee72-e016-11e7-9b26-c596856d7a71.png)

**Comment by StefMa** [comment]
Since #1134 is merged I'll close that for now. The sample is working on the current master branch.
It will may not fixed the sample in the binaries which are published over the release page. But I think that is not really related to that uikit sample but more a general issue which should not fixed in scope of that issue 👍
