### ISSUE TITLE
BUILD FAILED

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#1526]
fresh clone of master branch, new data dir:
`set KONAN_DATA_DIR=F:\Work\.konan`

```
F:\src\kotlin-native-msink>gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':common:mingw_x64Hash'.
> A problem occurred starting process 'command 'F:\work\.konan\dependencies\msys2-mingw-w64-x86_64-gcc-7.2.0-clang-llvm-5.0.0-windows-x86-64/bin/clang++''

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 2s
3 actionable tasks: 1 executed, 2 up-to-date
```

**Comment by ilmat192** [comment]
Did you execute `./gradlew dependencies:update` before running the build?

**Comment by msink** [comment]
Well, sorry - forgot about `dependencies:update`

Now error os different:
```
F:\src\kotlin-native-msink>gradlew build

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':klib:compileKonanAccessorsMingw_x64'.
> Classpath of the tool is empty: konanc
  Probably the 'konan.home' project property contains an incorrect path.
  Please change it to the compiler root directory and rerun the build.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

BUILD FAILED in 43s
32 actionable tasks: 29 executed, 3 up-to-date
```

**Comment by olonho** [comment]
This shall be fixed with https://github.com/JetBrains/kotlin-native/pull/1524/files

**Comment by msink** [comment]
Still failed:
`>git fetch origin pull/1524/head:dep`
`>git checkout dep`
`>gradlew clean build`

```
> Task :klib:test

org.jetbrains.kotlin.cli.klib.test.ContentsTest > accessors FAILED
    org.junit.ComparisonFailure at ContentsTest.kt:36

org.jetbrains.kotlin.cli.klib.test.ContentsTest > constructors FAILED
    org.junit.ComparisonFailure at ContentsTest.kt:36

org.jetbrains.kotlin.cli.klib.test.ContentsTest > topLevelFunctions FAILED
    org.junit.ComparisonFailure at ContentsTest.kt:36

org.jetbrains.kotlin.cli.klib.test.ContentsTest > objects FAILED
    org.junit.ComparisonFailure at ContentsTest.kt:36

org.jetbrains.kotlin.cli.klib.test.ContentsTest > methodModality FAILED                                           14:55
    org.junit.ComparisonFailure at ContentsTest.kt:36

org.jetbrains.kotlin.cli.klib.test.ContentsTest > functionModifiers FAILED
    org.junit.ComparisonFailure at ContentsTest.kt:36

org.jetbrains.kotlin.cli.klib.test.ContentsTest > enum FAILED
    org.junit.ComparisonFailure at ContentsTest.kt:36

org.jetbrains.kotlin.cli.klib.test.ContentsTest > classes FAILED
    org.junit.ComparisonFailure at ContentsTest.kt:36

9 tests completed, 8 failed


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':klib:test'.
> There were failing tests. See the report at: file:///F:/src/kotlin-native-msink/klib/build/reports/tests/test/index.html

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD FAILED in 4m 23s
97 actionable tasks: 93 executed, 4 up-to-date
```

**Comment by olonho** [comment]
What if you run `dist` target?

**Comment by msink** [comment]
```
k>gradlew dist

Deprecated Gradle features were used in this build, making it incompatible with Gradle 5.0.
See https://docs.gradle.org/4.6/userguide/command_line_interface.html#sec:command_line_warnings

BUILD SUCCESSFUL in 3s
57 actionable tasks: 2 executed, 55 up-to-date
```

**Comment by olonho** [comment]
OK, so `dist` works, and Ilya will fix the `build` target.

**Comment by msink** [comment]
https://gist.github.com/msink/9aaa10999b02382aa033bd85ff792117

**Comment by msink** [comment]
``` patch
>diff -u 1 2
--- 1   2018-04-23 15:41:25.307168300 +0500
+++ 2   2018-04-23 15:41:53.805402800 +0500
@@ -15,5 +15,6 @@
         protected val protectedSimple: Int = 0
         val simple: Int = 0
     }
+
 ]
 }
---

**Comment by ilmat192** [comment]
I've corrected line separators in klib tests: https://github.com/JetBrains/kotlin-native/pull/1524. The PR is already merged so you may check it.

@vvlevchenko What do you think about such a revision number? Is it ok to have it for non-CI builds?

**Comment by msink** [comment]
OK, now `gradlew clean build bundle` passed, and output file is `kotlin-native-windows-0.7-dev.zip`

But about first (my) fault:
Is additional manual phase `gradlew dependencies:update`  on fresh cloned repository  really needed?
IMHO if it cannot be somehow automated, at least there should be more meaningful error message.

**Comment by olonho** [comment]
It is required only once per machine, and is documented in README.md.

**Comment by msink** [comment]
Again broken:
```
e: F:\src\kotlin-native-msink\klib\src\test\kotlin\org\jetbrains\kotlin\cli\klib\test\ContentsTest.kt: (23, 29): Unresolved reference: preprocessor
e: F:\src\kotlin-native-msink\klib\src\test\kotlin\org\jetbrains\kotlin\cli\klib\test\ContentsTest.kt: (38, 28): Unresolved reference: convertLineSeparators
e: F:\src\kotlin-native-msink\klib\src\test\kotlin\org\jetbrains\kotlin\cli\klib\test\ContentsTest.kt: (39, 42): Unresolved reference: convertLineSeparators

FAILURE: Build failed with an exception.
```

**Comment by ilmat192** [comment]
Thanks, I'll investigate this.

**Comment by msink** [comment]
Again fixed, by #1571 :)
