### ISSUE TITLE
Cocoapods libraries with a dash in name

### ISSUE THREAD

**Issue by NiKlimenko** [JetBrains/kotlin-native#2884]
The gradle cocoapods plugin doesn't currently work with cocoapods dependencies that have a dash in the name.
During the build via xcode there is an error:

**> Task :cinteropLibPhoneNumber-iOSIos FAILED
Exception in thread "main" java.lang.Error: /var/folders/vx/_pzwpvl95_3gx_4fn15ry9nc0000gn/T/tmp8965756925637658485.m:1:9: fatal error: module 'libPhoneNumber' not found
	at org.jetbrains.kotlin.native.interop.indexer.UtilsKt.ensureNoCompileErrors(Utils.kt:133)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesASTFiles(ModuleSupport.kt:43)
	at org.jetbrains.kotlin.native.interop.indexer.ModuleSupportKt.getModulesInfo(ModuleSupport.kt:16)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.buildNativeLibrary(main.kt:349)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.processCLib(main.kt:214)
	at org.jetbrains.kotlin.native.interop.gen.jvm.MainKt.interop(main.kt:38)
	at org.jetbrains.kotlin.cli.utilities.InteropCompilerKt.invokeInterop(InteropCompiler.kt:67)
	at org.jetbrains.kotlin.cli.utilities.MainKt.main(main.kt:18)**

As you can see, cinterop tried to find the library by the wrong name (the first part of the name up to the dash).

How to reproduce: you can use the cocoapods sample placed in this repository. Just add another cocoapods dependency with the dashed name in build.gradle.kts and try to build from xcode.

**Comment by Syrou** [comment]
This is the same error as in https://github.com/JetBrains/kotlin-native/issues/2863 its not about dash, something else is wrong here

**Comment by NiKlimenko** [comment]
@ilmat192 hi, do you have any plans to solve this issue in the near future?

**Comment by ilmat192** [comment]
We are going to fix it but most probably not in the nearest release.

**Comment by jonasbark** [comment]
Another pod example: `SignalR-ObjC`

**Comment by Sonicskater** [comment]
Hello, experiencing this same issue with an internal library. However, we can't rename it as this breaks the compilation and I'm not allowed to make the changes required to fix that. How feasible would it be to do the cinterop myself?

**Comment by ilmat192** [comment]
I've investigated it a little bit deeper and it seems that we can workaround this issue by setting a custom module name at the user side.

@Sonicskater Please try to replace dashes with underscores in the name of the pod and specify this name as a `moduleName`:
```
cocoapods {
    pod("pod-name", "1.0", moduleName = "pod_name")
}
```

**Comment by ilmat192** [comment]
Fixed by the commit above.

**Comment by jeffdgr8** [comment]
I'm still experiencing this issue with the `CouchbaseLite-Enterprise` CocoaPods library, which has a dash in the name. I filed a [YouTrack issue](https://youtrack.jetbrains.com/issue/KT-44235) with details.

**Comment by CrispBull** [comment]
Same here, I'm also still experiencing this issue
