### ISSUE TITLE
OOM errors on MacOS

### ISSUE THREAD

**Issue by msink** [JetBrains/kotlin-native#3699]
My builds started to fail by OOM on MacOS, Linux and Windows are ok.
Probably something related to recently enabled as delault `* Output kind: STATIC_CACHE`

https://github.com/msink/kotlin-libui/runs/354427565
https://travis-ci.org/msink/kotlin-libui/jobs/626634874

**Comment by olonho** [comment]
Can you increase  memory limit for Gradle?

**Comment by msink** [comment]
Don't know - I do not have Mac available, and it is hard to experiment on public CI servers.

**Comment by homuroll** [comment]
It's probably due to recently turned on by default compiler daemon run inside Gradle. Adding `org.gradle.jvmargs=-Xmx2048m -XX:MaxPermSize=1024m` to `gradle.properties` should solve the issue.

**Comment by msink** [comment]
Increasing memory limit to
`org.gradle.jvmargs=-Xmx8g -XX:MaxPermSize=8g`
did help on github-workflow, but travis-ci still failed, with message
`No output has been received in the last 10m0s, this potentially indicates a stalled build or something wrong with the build itself.`

Gradle BuildScan on github - https://gradle.com/s/vc2hzh4lpmzo6
Here - task `:compose-runtime:linkDebugTestMacosx` runned `10m 1.590s`
IMHO too big regression campared to 1.3.61.

**Comment by homuroll** [comment]
That is definitely caches building, which is performed only once on the first build. But we've realised it's a problem and are working on prepopulating cache for stdlib and platform libraries and embedding it into the compiler bundle.

**Comment by olonho** [comment]
You could try to set `kotlin.native.disableCompilerDaemon=true` to disable daemon.

**Comment by msink** [comment]
Maybe, but real problem turned out that now every CI run on MacOS will take additional 10 minutes. 
IMHO it's major regression.

**Comment by olonho** [comment]
It will be fixed with EAP1 for macOS and iOS targets by precomputing caches. It happens only on the first run on that particular machine, and subsequent runs will be way faster. One could disable caches as well once https://upsource.jetbrains.com/kotlin/review/KOTLIN-CR-3664?filePath=/libraries/tools/kotlin-gradle-plugin/src/main/kotlin/org/jetbrains/kotlin/gradle/targets/native/tasks/KotlinNativeTasks.kt will be merged.

**Comment by msink** [comment]
Sure, but on CI server every run is "first", because it runs on clean image

**Comment by msink** [comment]
Fixed in 1.3.70-eap-28: 
`linkDebugTestMacosx	21.517s`
