### ISSUE TITLE
Error while building compiler : 'jni.h' file not found

### ISSUE THREAD

**Issue by kkumar326** [JetBrains/kotlin-native#921]
./gradlew dist is throwing error. I've openjdk 9 installed.

I've added jdk c libs for compiler in gradle files and yet it is throwing error.

I've posted the detailed problem here: https://stackoverflow.com/questions/46608148/kotlin-native-installation-error-jni-h-file-not-found

**Comment by kkumar326** [comment]
It's fixed now. I've updated the stackoverflow link with the fix.

**Comment by kajweb** [comment]
I try to fix the stackoverflow link.But it still failed.
`                KotlinPlatform.JVM -> listOf("", "linux", "darwin", "win32").map {
                    val javaHome = System.getProperty("java.home")
                    "-I/Library/Java/JavaVirtualMachines/jdk-9.jdk/Contents/Home/include/$it"
                    "-I$javaHome/../include/$it"
                }`

and I using OSX with oracle java9

**Comment by kkumar326** [comment]
Before that, you'll have to add java sdk include folder path in gradle as mentioned in the link:
cCompiler.args "-I/usr/lib/jvm/java-9-openjdk-amd64/include"
cCompiler.args "-I/usr/lib/jvm/java-9-openjdk-amd64/include/linux"

**Comment by kkumar326** [comment]
And either comment or remove this line: "-I$javaHome/../include/$it"

**Comment by kajweb** [comment]
I installed the java8 back。

**Comment by kkumar326** [comment]
Ok. It's working on java 9 though.
